SandwaveIo\Office365\Response\OrderSummaryResponse:
  exclusion_policy: ALL
  xml_root_name: OrderSummaryResponse_V1

  properties:

    status:
      expose: true
      type: SandwaveIo\Office365\Response\RequestStatus
      serialized_name: Status
      xml_list:
        inline: false
        entry_name: string

    pagedResult:
      expose: true
      type: SandwaveIo\Office365\Entity\PagedResult
      serialized_name: PagedResult
      xml_list:
        inline: false
        entry_name: OrderSummary_V1
