SandwaveIo\Office365\Response\RequestStatus:
  exclusion_policy: ALL

  properties:

    messages:
      expose: true
      type: array
      serialized_name: Messages

    code:
      expose: true
      type: string
      serialized_name: Code
