SandwaveIo\Office365\Response\TenantExistsResponse:
  exclusion_policy: ALL
  xml_root_name: MicrosoftTenantExistsCheckResponse_V1

  properties:

    status:
      expose: true
      type: SandwaveIo\Office365\Response\RequestStatus
      serialized_name: Status

    isExistingTenant:
      expose: true
      type: bool
      serialized_name: IsExistingTenant