SandwaveIo\Office365\Entity\Header\PartnerReferenceHeader:
  exclusion_policy: ALL

  properties:

    partnerReference:
      expose: true
      type: string
      serialized_name: PartnerReference

    dateCreated:
      expose: true
      type: DateTime<'Y-m-d\TH:i:s'>
      serialized_name: DateCreated
