SandwaveIo\Office365\Entity\Addon:
  exclusion_policy: ALL
  xml_root_name: NewCloudLicenseAddOnOrderRequest_V1

  properties:

    header:
      expose: true
      type: SandwaveIo\Office365\Entity\Header\PartnerReferenceHeader
      serialized_name: Header

    parentOrderId:
      expose: true
      type: int
      serialized_name: ParentOrderId

    productCode:
      expose: true
      type: string
      serialized_name: ProductCode

    quantity:
      expose: true
      type: int
      serialized_name: Quantity

    licenseKey:
      expose: true
      type: string
      serialized_name: LicenseKey
