SandwaveIo\Office365\Entity\Addon:
  exclusion_policy: ALL

  properties:

    header:
      expose: true
      type: SandwaveIo\Office365\Entity\Header\CustomerHeader
      serialized_name: Header

    parentOrderId:
      expose: true
      type: int
      serialized_name: ParentOrderId

    productCode:
      expose: true
      type: string
      serialized_name: ProductCode

    quantity:
      expose: true
      type: int
      serialized_name: Quantity
