SandwaveIo\Office365\Entity\CloudAgreementContact:
  exclusion_policy: ALL

  properties:

    header:
      expose: true
      type: SandwaveIo\Office365\Entity\Header\CustomerHeader
      serialized_name: Header

    customerId:
      expose: true
      type: int
      serialized_name: CustomerId

    contact:
      expose: true
      type: SandwaveIo\Office365\Entity\CloudAgreementContact_V1\AgreementContact
      serialized_name: AgreementContact
