SandwaveIo\Office365\Entity\Addon:

  exclusion_policy: ALL

  xml_root_name: NewCloudLicenseAddOnOrderResponse_V1

  xml_data_node: CloudLicenseAddOn

  properties:

    status:
      expose: true

      type: string

      xml_list:
        inline: false
        entry_name: Status
