SandwaveIo\Office365\Entity\CloudLicense:

  exclusion_policy: ALL

  xml_root_name: NewCloudLicenseOrderResponse_V2

  xml_data_node: CloudLicense

  properties:

    status:
      expose: true

      type: string

      xml_list:
        inline: false
        entry_name: Status
