SandwaveIo\Office365\Entity\CloudAgreementContact:
  exclusion_policy: ALL

  xml_root_name: NewCloudAgreementContactRequest_V1

  properties:

    header:
      expose: true
      type: SandwaveIo\Office365\Entity\Header\PartnerReferenceHeader
      serialized_name: Header

    customerId:
      expose: true
      type: int
      serialized_name: CustomerId

    contact:
      expose: true
      type: SandwaveIo\Office365\Entity\AgreementContact
      serialized_name: AgreementContact
