SandwaveIo\Office365\Entity\Customer:
  exclusion_policy: ALL

  xml_root_name: ModifyCustomerResponse_V3

  transformer:
    response: \SandwaveIo\Office365\Transformer\CustomerResponseXmlTransformer
