SandwaveIo\Office365\Entity\Customer:
  exclusion_policy: ALL

  xml_root_name: NewCustomerRequest_V3

  properties:

    header:
      expose: true
      type: SandwaveIo\Office365\Entity\Header\PartnerReferenceHeader
      serialized_name: Header

    name:
      expose: true
      type: string
      serialized_name: Name

    street:
      expose: true
      type: string
      serialized_name: Street

    houseNr:
      expose: true
      type: int
      serialized_name: HouseNr

    houseNrExtension:
      expose: true
      type: string
      serialized_name: HouseNrExtension

    zipCode:
        expose: true
        type: string
        serialized_name: ZipCode

    city:
      expose: true
      type: string
      serialized_name: City

    countryCode:
      expose: true
      type: string
      serialized_name: CountryCode

    phone1:
      expose: true
      type: string
      serialized_name: Phone1

    phone2:
      expose: true
      type: string
      serialized_name: Phone2

    fax:
      expose: true
      type: string
      serialized_name: Fax

    email:
      expose: true
      type: string
      serialized_name: Email

    website:
      expose: true
      type: string
      serialized_name: Website

    debitNr:
      expose: true
      type: string
      serialized_name: DebitNr

    iban:
      expose: true
      type: string
      serialized_name: IBAN

    bic:
      expose: true
      type: string
      serialized_name: BIC

    vatNr:
      expose: true
      type: string
      serialized_name: VATNr

    legalStatus:
      expose: true
      type: string
      serialized_name: LegalStatus

    externalId:
      expose: true
      type: string
      serialized_name: ExternalId

    chamberOfCommerceNr:
      expose: true
      type: string
      serialized_name: ChamberOfCommerceNr
