SandwaveIo\Office365\Entity\Customer:
  exclusion_policy: ALL

  xml_root_name: NewCustomerResponse_V3

  properties:

  transformer:
    response: \SandwaveIo\Office365\Transformer\CustomerResponseXmlTransformer
