SandwaveIo\Office365\Entity\OrderModifyQuantity:
  exclusion_policy: ALL
  xml_root_name: ModifyOrderQuantityRequest_V1

  properties:

    header:
      expose: true
      type: SandwaveIo\Office365\Entity\Header\PartnerReferenceHeader
      serialized_name: Header

    orderId:
      expose: true
      type: int
      serialized_name: OrderId

    quantity:
      expose: true
      type: int
      serialized_name: Quantity

    delta:
      expose: true
      type: bool
      serialized_name: IsDelta

    upgradeOrderId:
      expose: true
      type: int
      serialized_name: UpgradeOrderId
