SandwaveIo\Office365\Entity\Tenant:
  exclusion_policy: ALL
  xml_root_name: MicrosoftTenantExistsCheckRequest_V1

  properties:

    tenantName:
      expose: true
      type: string
      serialized_name: TenantName
