SandwaveIo\Office365\Entity\Terminate:

  exclusion_policy: ALL

  xml_root_name: TerminateOrderRequest_V2

  properties:

    header:
      expose: true
      type: SandwaveIo\Office365\Entity\Header\PartnerReferenceHeader
      serialized_name: Header

    orderId:
      expose: true
      type: string
      serialized_name: OrderId

    desiredTerminateDate:
      expose: true
      type: DateTime<'Y-m-d'>
      serialized_name: DesiredTerminateDate

    terminateAsSoonAsPossible:
      expose: true
      type: bool
      serialized_name: TerminateAsSoonAsPossible
